// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.15.5
// source: dynago-parameter.proto

package messages

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

//later repeated message types for list types
type ValueTypeParameter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to ParameterOneof:
	//	*ValueTypeParameter_IntegerValue
	//	*ValueTypeParameter_StringValue
	//	*ValueTypeParameter_DoubleValue
	//	*ValueTypeParameter_BoolValue
	ParameterOneof isValueTypeParameter_ParameterOneof `protobuf_oneof:"parameter_oneof"`
}

func (x *ValueTypeParameter) Reset() {
	*x = ValueTypeParameter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_dynago_parameter_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ValueTypeParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValueTypeParameter) ProtoMessage() {}

func (x *ValueTypeParameter) ProtoReflect() protoreflect.Message {
	mi := &file_dynago_parameter_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValueTypeParameter.ProtoReflect.Descriptor instead.
func (*ValueTypeParameter) Descriptor() ([]byte, []int) {
	return file_dynago_parameter_proto_rawDescGZIP(), []int{0}
}

func (m *ValueTypeParameter) GetParameterOneof() isValueTypeParameter_ParameterOneof {
	if m != nil {
		return m.ParameterOneof
	}
	return nil
}

func (x *ValueTypeParameter) GetIntegerValue() int32 {
	if x, ok := x.GetParameterOneof().(*ValueTypeParameter_IntegerValue); ok {
		return x.IntegerValue
	}
	return 0
}

func (x *ValueTypeParameter) GetStringValue() string {
	if x, ok := x.GetParameterOneof().(*ValueTypeParameter_StringValue); ok {
		return x.StringValue
	}
	return ""
}

func (x *ValueTypeParameter) GetDoubleValue() float64 {
	if x, ok := x.GetParameterOneof().(*ValueTypeParameter_DoubleValue); ok {
		return x.DoubleValue
	}
	return 0
}

func (x *ValueTypeParameter) GetBoolValue() bool {
	if x, ok := x.GetParameterOneof().(*ValueTypeParameter_BoolValue); ok {
		return x.BoolValue
	}
	return false
}

type isValueTypeParameter_ParameterOneof interface {
	isValueTypeParameter_ParameterOneof()
}

type ValueTypeParameter_IntegerValue struct {
	IntegerValue int32 `protobuf:"varint,1,opt,name=integerValue,proto3,oneof"`
}

type ValueTypeParameter_StringValue struct {
	StringValue string `protobuf:"bytes,2,opt,name=stringValue,proto3,oneof"`
}

type ValueTypeParameter_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=doubleValue,proto3,oneof"`
}

type ValueTypeParameter_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=boolValue,proto3,oneof"`
}

func (*ValueTypeParameter_IntegerValue) isValueTypeParameter_ParameterOneof() {}

func (*ValueTypeParameter_StringValue) isValueTypeParameter_ParameterOneof() {}

func (*ValueTypeParameter_DoubleValue) isValueTypeParameter_ParameterOneof() {}

func (*ValueTypeParameter_BoolValue) isValueTypeParameter_ParameterOneof() {}

var File_dynago_parameter_proto protoreflect.FileDescriptor

var file_dynago_parameter_proto_rawDesc = []byte{
	0x0a, 0x16, 0x64, 0x79, 0x6e, 0x61, 0x67, 0x6f, 0x2d, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x06, 0x64, 0x79, 0x6e, 0x61, 0x67, 0x6f,
	0x22, 0xb5, 0x01, 0x0a, 0x12, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x54, 0x79, 0x70, 0x65, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x65, 0x74, 0x65, 0x72, 0x12, 0x24, 0x0a, 0x0c, 0x69, 0x6e, 0x74, 0x65, 0x67,
	0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52,
	0x0c, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x65, 0x72, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x22, 0x0a,
	0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x48, 0x00, 0x52, 0x0b, 0x73, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x56, 0x61, 0x6c, 0x75,
	0x65, 0x12, 0x22, 0x0a, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65, 0x56, 0x61, 0x6c, 0x75, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x48, 0x00, 0x52, 0x0b, 0x64, 0x6f, 0x75, 0x62, 0x6c, 0x65,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1e, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6c, 0x56, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x08, 0x48, 0x00, 0x52, 0x09, 0x62, 0x6f, 0x6f, 0x6c,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x42, 0x11, 0x0a, 0x0f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x65, 0x74,
	0x65, 0x72, 0x5f, 0x6f, 0x6e, 0x65, 0x6f, 0x66, 0x42, 0x23, 0x5a, 0x21, 0x67, 0x69, 0x74, 0x68,
	0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x6b, 0x6d, 0x70, 0x30, 0x39, 0x31, 0x2f, 0x64, 0x79,
	0x6e, 0x61, 0x67, 0x6f, 0x2f, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_dynago_parameter_proto_rawDescOnce sync.Once
	file_dynago_parameter_proto_rawDescData = file_dynago_parameter_proto_rawDesc
)

func file_dynago_parameter_proto_rawDescGZIP() []byte {
	file_dynago_parameter_proto_rawDescOnce.Do(func() {
		file_dynago_parameter_proto_rawDescData = protoimpl.X.CompressGZIP(file_dynago_parameter_proto_rawDescData)
	})
	return file_dynago_parameter_proto_rawDescData
}

var file_dynago_parameter_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_dynago_parameter_proto_goTypes = []interface{}{
	(*ValueTypeParameter)(nil), // 0: dynago.ValueTypeParameter
}
var file_dynago_parameter_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_dynago_parameter_proto_init() }
func file_dynago_parameter_proto_init() {
	if File_dynago_parameter_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_dynago_parameter_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ValueTypeParameter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_dynago_parameter_proto_msgTypes[0].OneofWrappers = []interface{}{
		(*ValueTypeParameter_IntegerValue)(nil),
		(*ValueTypeParameter_StringValue)(nil),
		(*ValueTypeParameter_DoubleValue)(nil),
		(*ValueTypeParameter_BoolValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_dynago_parameter_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_dynago_parameter_proto_goTypes,
		DependencyIndexes: file_dynago_parameter_proto_depIdxs,
		MessageInfos:      file_dynago_parameter_proto_msgTypes,
	}.Build()
	File_dynago_parameter_proto = out.File
	file_dynago_parameter_proto_rawDesc = nil
	file_dynago_parameter_proto_goTypes = nil
	file_dynago_parameter_proto_depIdxs = nil
}
